### ISSUE TITLE
update /about section

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#116]
this section

> In 2022 the E-commerce Berlin Expo will take place for the 6th time. When we chose to expand the proven Expo formula back in 2018, we decided to add the Networking Party a day before the actual event.

 is not updatable via localize so please provide updates here  - i will update the code

**Comment by marek-berlin** [comment]
ENG

In 2023 E-commerce Germany Awards will take place for the 6th time. When we chose to expand the proven Expo formula back in 2018, we decided to add the Networking Party a day before the actual event.
We immediately knew that an additional evening spent with the industry leaders would be highly valuable for all participants. Since then, it has become an awaiting tradition for e-commerce professionals all over Europe, and over 3000 guests had a chance to celebrate such an evening with us.
The Party consists of two parts: a pure Networking party and the E-commerce Germany Awards Ceremony.

DE

Die E-Commerce Germany Awards findet im Jahr 2023 zum 6. Mal statt. Als wir uns 2018 für eine Erweiterung der etablierten Expo-Formel entschieden haben, haben wir die Networking Party einen Tag vor der eigentlichen Veranstaltung eingeführt.
Uns war sofort klar, dass ein gemeinsamer Abend mit den Branchenführern für alle Teilnehmer sehr wertvoll sein würde. Seitdem ist sie zu einer erwarteten Tradition für E-Commerce-Profis in ganz Europa geworden, und über 3000 Gäste hatten die Gelegenheit, einen solchen Abend mit uns zu feiern.
Die Party besteht aus zwei Teilen: einer reinen Networking-Party und der E-commerce Germany Awards Ceremony.

**Comment by az** [comment]
moved to localise -> asset id: "awards.about.body" (markdown enabled) / via fa8fa31b4d6b243fd2ab6473c7792263d09cb048
